import React from 'react';
import { MenuItem, ServiceItem } from './types';
import { 
  BedDouble, 
  Shirt, 
  Car, 
  Bath,
  Wind,
  Pill,
  Luggage,
  Bell,
  Ban,
  Wrench,
  SprayCan
} from 'lucide-react';

export const ROOM_NUMBER = "6";
export const GUEST_NAME = "Sayın Misafirimiz";

export const HOTEL_INFO = {
  wifiName: "forGuest_Secure",
  wifiPass: "Welcome2025",
  checkout: "11:00",
  breakfast: "06:30 - 10:30",
  receptionPhone: "+902125550000",
  whatsappNumber: "905551234567" // Example number format without +
};

export const TRANSLATIONS = {
  tr: {
    welcome: "Hoşgeldiniz",
    room: "Oda",
    wifi: "WiFi Ağı",
    checkout: "Çıkış Saati",
    food: "Yemek",
    foodDesc: "Odaya servis lezzetler",
    foodHours: "08:30 - 01:30",
    market: "Market",
    marketDesc: "Atıştırmalık & İçecek",
    marketHours: "08:30 - 03:30",
    services: "Hizmetler",
    servicesDesc: "Housekeeping & Teknik",
    reception: "Resepsiyon",
    receptionDesc: "7/24 Canlı Destek",
    back: "Geri",
    addToCart: "Sepete Ekle",
    popular: "POPÜLER",
    marketFee: "Market ürünlerinde ek olarak %12.5 servis hizmet bedeli uygulanmaktadır.",
    recommended: "Yanına Yakışacaklar",
    emptyCart: "Sepetiniz şu an boş.",
    returnMenu: "Menüye Dön",
    total: "Toplam Tutar",
    confirmOrder: "Siparişi Onayla",
    foodTotal: "Yemek Tutarı",
    marketTotal: "Market Tutarı",
    serviceFee: "Hizmet Bedeli",
    grandTotal: "Genel Toplam",
    cancel: "İptal",
    approve: "Siparişi Tamamla",
    serviceRequest: "Hizmet Talebi",
    serviceRequestDesc: "Oda servisi ve teknik destek hizmetleri.",
    confirmService: "Bu hizmeti talep etmek istediğinize emin misiniz?",
    request: "Talep Et",
    giveUp: "Vazgeç",
    loginTitle: "Sipariş Doğrulama",
    loginDesc: "Siparişi tamamlamak için resepsiyon kodunu giriniz.",
    enterCode: "Resepsiyon Kodu",
    codeError: "Hatalı kod, lütfen tekrar deneyiniz.",
    loginBtn: "Doğrula ve Tamamla",
    noCode: "Kodunuz yok mu?",
    callReception: "Resepsiyonu Ara",
    writeWhatsapp: "WhatsApp'tan Yaz",
    contactReception: "Resepsiyon İletişim",
    contactDesc: "Nasıl yardımcı olabiliriz?",
    orderReceived: "Sipariş Oluşturuldu",
    orderReceivedDesc: "Siparişiniz başarıyla sisteme düşmüştür ve işleme alınmıştır. Ortalama servis süresi 35 dakikadır.",
    serviceSent: "talebi iletildi",
    added: "eklendi",
    rateUs: "Bizi Değerlendirin",
    rateDesc: "Deneyiminizi paylaşın",
    diningTitle: "In-Room Dining",
    marketTitle: "Mini Market",
    cats: {
      all: 'Tümü',
      starters: 'Başlangıçlar',
      mains: 'Ana Yemekler',
      desserts: 'Tatlılar',
      snacks: 'Atıştırmalık',
      drinks: 'İçecekler',
      personal: 'Kişisel Bakım'
    },
    serviceNames: {
      towel: 'Ekstra Havlu',
      pillow: 'Yastık İsteği',
      soap: 'Banyo Seti',
      laundry: 'Kuru Temizleme',
      taxi: 'Taksi Çağır',
      ac: 'Klima Kontrolü',
      luggage: 'Bavul Taşıma',
      wakeup: 'Uyandırma Servisi',
      dnd: 'Rahatsız Etmeyin',
      tech: 'Teknik Destek',
      clean: 'Oda Temizliği'
    }
  },
  en: {
    welcome: "Welcome",
    room: "Room",
    wifi: "WiFi Network",
    checkout: "Check-out",
    food: "Dining",
    foodDesc: "In-room dining service",
    foodHours: "08:30 - 01:30",
    market: "Market",
    marketDesc: "Snacks & Drinks",
    marketHours: "08:30 - 03:30",
    services: "Services",
    servicesDesc: "Housekeeping & Tech",
    reception: "Reception",
    receptionDesc: "24/7 Live Support",
    back: "Back",
    addToCart: "Add to Cart",
    popular: "POPULAR",
    marketFee: "A 12.5% service fee applies to market items.",
    recommended: "Pairs Well With",
    emptyCart: "Your cart is empty.",
    returnMenu: "Return to Menu",
    total: "Total Amount",
    confirmOrder: "Checkout",
    foodTotal: "Food Total",
    marketTotal: "Market Total",
    serviceFee: "Service Fee",
    grandTotal: "Grand Total",
    cancel: "Cancel",
    approve: "Complete Order",
    serviceRequest: "Service Request",
    serviceRequestDesc: "Room service and technical support.",
    confirmService: "Are you sure you want to request this service?",
    request: "Request",
    giveUp: "Cancel",
    loginTitle: "Order Verification",
    loginDesc: "Enter reception code to complete order.",
    enterCode: "Reception Code",
    codeError: "Invalid code, please try again.",
    loginBtn: "Verify & Order",
    noCode: "Don't have a code?",
    callReception: "Call Reception",
    writeWhatsapp: "Write on WhatsApp",
    contactReception: "Contact Reception",
    contactDesc: "How can we help you?",
    orderReceived: "Order Created",
    orderReceivedDesc: "Your order has been successfully created and is being processed. Estimated time: 35 min.",
    serviceSent: "request sent",
    added: "added",
    rateUs: "Rate Us",
    rateDesc: "Share your experience",
    diningTitle: "In-Room Dining",
    marketTitle: "Mini Market",
    cats: {
      all: 'All',
      starters: 'Starters',
      mains: 'Mains',
      desserts: 'Desserts',
      snacks: 'Snacks',
      drinks: 'Drinks',
      personal: 'Personal Care'
    },
    serviceNames: {
      towel: 'Extra Towel',
      pillow: 'Extra Pillow',
      soap: 'Bath Kit',
      laundry: 'Dry Cleaning',
      taxi: 'Call Taxi',
      ac: 'AC Control',
      luggage: 'Bellboy',
      wakeup: 'Wake-up Call',
      dnd: 'Do Not Disturb',
      tech: 'Tech Support',
      clean: 'Room Cleaning'
    }
  },
  ar: {
    welcome: "أهلاً بك",
    room: "غرفة",
    wifi: "شبكة واي فاي",
    checkout: "الدفع",
    food: "طعام",
    foodDesc: "خدمة الغرف",
    foodHours: "08:30 - 01:30",
    market: "السوق",
    marketDesc: "وجبات خفيفة ومشروبات",
    marketHours: "08:30 - 03:30",
    services: "خدمات",
    servicesDesc: "تدبير منزلي وتقنية",
    reception: "استقبال",
    receptionDesc: "دعم مباشر 24/7",
    back: "رجوع",
    addToCart: "أضف إلى السلة",
    popular: "شائع",
    marketFee: "تطبق رسوم خدمة 12.5٪ على منتجات السوق.",
    recommended: "يقترن بشكل جيد مع",
    emptyCart: "سلتك فارغة.",
    returnMenu: "العودة للقائمة",
    total: "الإجمالي",
    confirmOrder: "الدفع",
    foodTotal: "مجموع الطعام",
    marketTotal: "مجموع السوق",
    serviceFee: "رسوم الخدمة",
    grandTotal: "المجموع الكلي",
    cancel: "إلغاء",
    approve: "إكمال الطلب",
    serviceRequest: "طلب خدمة",
    serviceRequestDesc: "خدمة الغرف والدعم الفني.",
    confirmService: "هل أنت متأكد أنك تريد طلب هذه الخدمة؟",
    request: "طلب",
    giveUp: "إلغاء",
    loginTitle: "تأكيد الطلب",
    loginDesc: "أدخل رمز الاستقبال لإكمال الطلب.",
    enterCode: "رمز الاستقبال",
    codeError: "رمز غير صالح ، حاول مرة أخرى.",
    loginBtn: "تحقق واطلب",
    noCode: "ليس لديك رمز؟",
    callReception: "اتصل بالاستقبال",
    writeWhatsapp: "واتساب",
    contactReception: "اتصل بالاستقبال",
    contactDesc: "كيف يمكننا مساعدتك؟",
    orderReceived: "تم إنشاء الطلب",
    orderReceivedDesc: "تم إنشاء طلبك بنجاح وتجري معالجته. الوقت المقدر: 35 دقيقة.",
    serviceSent: "تم إرسال الطلب",
    added: "تمت الإضافة",
    rateUs: "قيمنا",
    rateDesc: "شارك تجربتك",
    diningTitle: "توي طعام",
    marketTitle: "سوق صغير",
    cats: {
      all: 'الكل',
      starters: 'مقبلات',
      mains: 'أطباق رئيسية',
      desserts: 'حلويات',
      snacks: 'وجبات خفيفة',
      drinks: 'مشروبات',
      personal: 'عناية شخصية'
    },
    serviceNames: {
      towel: 'منشفة إضافية',
      pillow: 'وسادة إضافية',
      soap: 'مجموعة الحمام',
      laundry: 'تنين جاف',
      taxi: 'طلب تاكسي',
      ac: 'تكييف',
      luggage: 'حمال حقائب',
      wakeup: 'مكالمة إيقاظ',
      dnd: 'لا تزعج',
      tech: 'دعم فني',
      clean: 'تنظيف الغرفة'
    }
  }
};

export const FOOD_CATEGORIES = [
  { id: 'all' },
  { id: 'starters' },
  { id: 'mains' },
  { id: 'desserts' },
];

export const MARKET_CATEGORIES = [
  { id: 'all' },
  { id: 'snacks' },
  { id: 'drinks' },
  { id: 'personal' },
];

export const MENU_ITEMS: MenuItem[] = [
  // --- YEMEK (FOOD) ---
  {
    id: '1',
    name: 'Kulüp Sandviç',
    description: 'Tavuk, füme et, marul, domates ve yumurta ile üç katlı lezzet.',
    price: 380.00,
    category: 'mains',
    type: 'food',
    image: 'https://picsum.photos/id/1080/400/300',
    popular: true,
  },
  {
    id: '2',
    name: 'Sezar Salatası',
    description: 'Taze marul, parmesan, kruton ve özel sos.',
    price: 290.00,
    category: 'starters',
    type: 'food',
    image: 'https://picsum.photos/id/1081/400/300',
  },
  {
    id: '3',
    name: 'Wagyu Burger',
    description: 'Premium köfte, brioche ekmek, yıllanmış cheddar, trüflü patates.',
    price: 550.00,
    category: 'mains',
    type: 'food',
    image: 'https://picsum.photos/id/163/400/300',
    popular: true,
  },
  {
    id: '4',
    name: 'Tiramisu',
    description: 'Espresso ile ıslatılmış kedidili, mascarpone peyniri.',
    price: 220.00,
    category: 'desserts',
    type: 'food',
    image: 'https://picsum.photos/id/292/400/300',
  },
  {
    id: '5',
    name: 'Artisan Pizza',
    description: 'San Marzano domates sosu, manda mozzarellası, fesleğen.',
    price: 420.00,
    category: 'mains',
    type: 'food',
    image: 'https://picsum.photos/id/82/400/300',
  },
  {
    id: '8',
    name: 'Trüflü Patates',
    description: 'Parmesan ve trüf yağı ile harmanlanmış el yapımı patates.',
    price: 180.00,
    category: 'starters',
    type: 'food',
    image: 'https://picsum.photos/id/493/400/300',
  },
  
  // --- MARKET ---
  {
    id: 'm1',
    name: 'Cola Zero (330ml)',
    description: 'Soğuk servis edilir.',
    price: 80.00,
    category: 'drinks',
    type: 'market',
    image: 'https://picsum.photos/id/437/400/300',
  },
  {
    id: 'm2',
    name: 'Su (Cam Şişe 750ml)',
    description: 'Premium doğal kaynak suyu.',
    price: 45.00,
    category: 'drinks',
    type: 'market',
    image: 'https://picsum.photos/id/400/400/300',
  },
  {
    id: 'm3',
    name: 'Karışık Kuruyemiş',
    description: '150gr kavrulmuş lüks karışık kuruyemiş paketi.',
    price: 140.00,
    category: 'snacks',
    type: 'market',
    image: 'https://picsum.photos/id/307/400/300',
  },
  {
    id: 'm4',
    name: 'Çikolata Bar',
    description: 'Sütlü fıstıklı premium çikolata.',
    price: 65.00,
    category: 'snacks',
    type: 'market',
    image: 'https://picsum.photos/id/1060/400/300',
  },
  {
    id: 'm5',
    name: 'Diş Macunu & Fırçası',
    description: 'Seyahat boyu bakım seti.',
    price: 90.00,
    category: 'personal',
    type: 'market',
    image: 'https://picsum.photos/id/106/400/300',
  },
  {
    id: 'm6',
    name: 'Meyve Tabağı',
    description: 'Mevsim meyvelerinden oluşan taze tabak.',
    price: 120.00,
    category: 'snacks',
    type: 'market',
    image: 'https://picsum.photos/id/824/400/300',
  }
];

export const SERVICE_ITEMS: ServiceItem[] = [
  { id: 'clean', nameKey: 'clean', icon: <SprayCan className="w-6 h-6 text-cyan-400" strokeWidth={1.5} />, category: 'housekeeping' },
  { id: 'towel', nameKey: 'towel', icon: <Bath className="w-6 h-6 text-blue-400" strokeWidth={1.5} />, category: 'housekeeping' },
  { id: 'pillow', nameKey: 'pillow', icon: <BedDouble className="w-6 h-6 text-indigo-400" strokeWidth={1.5} />, category: 'housekeeping' },
  { id: 'soap', nameKey: 'soap', icon: <Pill className="w-6 h-6 text-rose-400" strokeWidth={1.5} />, category: 'housekeeping' },
  { id: 'laundry', nameKey: 'laundry', icon: <Shirt className="w-6 h-6 text-violet-400" strokeWidth={1.5} />, category: 'housekeeping' },
  { id: 'luggage', nameKey: 'luggage', icon: <Luggage className="w-6 h-6 text-amber-400" strokeWidth={1.5} />, category: 'front-desk' },
  { id: 'taxi', nameKey: 'taxi', icon: <Car className="w-6 h-6 text-yellow-400" strokeWidth={1.5} />, category: 'transport' },
  { id: 'ac', nameKey: 'ac', icon: <Wind className="w-6 h-6 text-sky-400" strokeWidth={1.5} />, category: 'tech' },
  { id: 'tech', nameKey: 'tech', icon: <Wrench className="w-6 h-6 text-slate-300" strokeWidth={1.5} />, category: 'tech' },
  { id: 'wakeup', nameKey: 'wakeup', icon: <Bell className="w-6 h-6 text-orange-400" strokeWidth={1.5} />, category: 'front-desk' },
  { id: 'dnd', nameKey: 'dnd', icon: <Ban className="w-6 h-6 text-red-500" strokeWidth={1.5} />, category: 'front-desk' },
];